{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/oduolaidrisA/Scientific-Machine-Learning/blob/main/data_generation.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "5nl9tA5kB9Z6"
      },
      "outputs": [],
      "source": [
        "import torch\n",
        "import math\n",
        "\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib\n",
        "\n",
        "from timeit import default_timer\n",
        "import scipy.io"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "rUEVnPr4BBrz"
      },
      "outputs": [],
      "source": [
        "class GaussianRF(object):\n",
        "\n",
        "    def __init__(self, dim, size, alpha=2, tau=3, sigma=None, boundary=\"periodic\", device=None):\n",
        "\n",
        "        self.dim = dim\n",
        "        self.device = device\n",
        "\n",
        "        if sigma is None:\n",
        "            sigma = tau**(0.5*(2*alpha - self.dim))\n",
        "\n",
        "        k_max = size//2\n",
        "\n",
        "        if dim == 1:\n",
        "            k = torch.cat((torch.arange(start=0, end=k_max, step=1, device=device), \\\n",
        "                           torch.arange(start=-k_max, end=0, step=1, device=device)), 0)\n",
        "\n",
        "            self.sqrt_eig = size*math.sqrt(2.0)*sigma*((4*(math.pi**2)*(k**2) + tau**2)**(-alpha/2.0))\n",
        "            self.sqrt_eig[0] = 0.0\n",
        "\n",
        "        elif dim == 2:\n",
        "            wavenumers = torch.cat((torch.arange(start=0, end=k_max, step=1, device=device), \\\n",
        "                                    torch.arange(start=-k_max, end=0, step=1, device=device)), 0).repeat(size,1)\n",
        "\n",
        "            k_x = wavenumers.transpose(0,1)\n",
        "            k_y = wavenumers\n",
        "\n",
        "            self.sqrt_eig = (size**2)*math.sqrt(2.0)*sigma*((4*(math.pi**2)*(k_x**2 + k_y**2) + tau**2)**(-alpha/2.0))\n",
        "            self.sqrt_eig[0,0] = 0.0\n",
        "\n",
        "        elif dim == 3:\n",
        "            wavenumers = torch.cat((torch.arange(start=0, end=k_max, step=1, device=device), \\\n",
        "                                    torch.arange(start=-k_max, end=0, step=1, device=device)), 0).repeat(size,size,1)\n",
        "\n",
        "            k_x = wavenumers.transpose(1,2)\n",
        "            k_y = wavenumers\n",
        "            k_z = wavenumers.transpose(0,2)\n",
        "\n",
        "            self.sqrt_eig = (size**3)*math.sqrt(2.0)*sigma*((4*(math.pi**2)*(k_x**2 + k_y**2 + k_z**2) + tau**2)**(-alpha/2.0))\n",
        "            self.sqrt_eig[0,0,0] = 0.0\n",
        "\n",
        "        self.size = []\n",
        "        for j in range(self.dim):\n",
        "            self.size.append(size)\n",
        "\n",
        "        self.size = tuple(self.size)\n",
        "\n",
        "    def sample(self, N):\n",
        "\n",
        "        real = torch.randn(N, *self.size, device=self.device)\n",
        "        imag = torch.randn(N, *self.size, device=self.device)\n",
        "        coeff = torch.complex(real, imag)\n",
        "\n",
        "        coeff = self.sqrt_eig * coeff\n",
        "\n",
        "        u = torch.fft.ifft(coeff, dim=self.dim, norm=\"backward\").real\n",
        "\n",
        "        return u"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "background_save": true,
          "base_uri": "https://localhost:8080/"
        },
        "id": "JDtOGE71BmYL",
        "outputId": "e4851ae0-d794-4174-8139-afc31cdd4015"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "0 20 1454.7499069259998\n",
            "1 40 2908.6630573380003\n"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "ERROR:root:Internal Python error in the inspect module.\n",
            "Below is the traceback from this internal error.\n",
            "\n",
            "ERROR:root:Internal Python error in the inspect module.\n",
            "Below is the traceback from this internal error.\n",
            "\n",
            "ERROR:root:Internal Python error in the inspect module.\n",
            "Below is the traceback from this internal error.\n",
            "\n"
          ]
        },
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
            "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
            "  File \"<ipython-input-8-6d3c60b8f943>\", line 165, in <cell line: 0>\n",
            "    sol, sol_t = navier_stokes_2d(w0, f, 1e-3, 50.0, 1e-4, record_steps)\n",
            "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"<ipython-input-8-6d3c60b8f943>\", line None, in navier_stokes_2d\n",
            "KeyboardInterrupt\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n",
            "    stb = value._render_traceback_()\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
            "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
            "    return f(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
            "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
            "                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/inspect.py\", line 1739, in getinnerframes\n",
            "    traceback_info = getframeinfo(tb, context)\n",
            "                     ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/inspect.py\", line 1686, in getframeinfo\n",
            "    start = lineno - 1 - context//2\n",
            "            ~~~~~~~^~~\n",
            "TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
            "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
            "  File \"<ipython-input-8-6d3c60b8f943>\", line 165, in <cell line: 0>\n",
            "    sol, sol_t = navier_stokes_2d(w0, f, 1e-3, 50.0, 1e-4, record_steps)\n",
            "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"<ipython-input-8-6d3c60b8f943>\", line None, in navier_stokes_2d\n",
            "KeyboardInterrupt\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n",
            "    stb = value._render_traceback_()\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n",
            "    if (await self.run_code(code, result,  async_=asy)):\n",
            "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n",
            "    self.showtraceback(running_compiled_code=True)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n",
            "    stb = self.InteractiveTB.structured_traceback(etype,\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
            "    return FormattedTB.structured_traceback(\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
            "    return VerboseTB.structured_traceback(\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n",
            "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
            "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
            "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
            "                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
            "    return len(records), 0\n",
            "           ^^^^^^^^^^^^\n",
            "TypeError: object of type 'NoneType' has no len()\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n",
            "    stb = value._render_traceback_()\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
            "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
            "    return f(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
            "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
            "                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/inspect.py\", line 1739, in getinnerframes\n",
            "    traceback_info = getframeinfo(tb, context)\n",
            "                     ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/inspect.py\", line 1686, in getframeinfo\n",
            "    start = lineno - 1 - context//2\n",
            "            ~~~~~~~^~~\n",
            "TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
            "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
            "  File \"<ipython-input-8-6d3c60b8f943>\", line 165, in <cell line: 0>\n",
            "    sol, sol_t = navier_stokes_2d(w0, f, 1e-3, 50.0, 1e-4, record_steps)\n",
            "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"<ipython-input-8-6d3c60b8f943>\", line None, in navier_stokes_2d\n",
            "KeyboardInterrupt\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n",
            "    stb = value._render_traceback_()\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n",
            "    if (await self.run_code(code, result,  async_=asy)):\n",
            "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n",
            "    self.showtraceback(running_compiled_code=True)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n",
            "    stb = self.InteractiveTB.structured_traceback(etype,\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
            "    return FormattedTB.structured_traceback(\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
            "    return VerboseTB.structured_traceback(\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n",
            "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
            "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
            "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
            "                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
            "    return len(records), 0\n",
            "           ^^^^^^^^^^^^\n",
            "TypeError: object of type 'NoneType' has no len()\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n",
            "    stb = value._render_traceback_()\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n",
            "    return runner(coro)\n",
            "           ^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n",
            "    coro.send(None)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n",
            "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
            "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n",
            "    self.showtraceback()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n",
            "    stb = self.InteractiveTB.structured_traceback(etype,\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
            "    return FormattedTB.structured_traceback(\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
            "    return VerboseTB.structured_traceback(\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n",
            "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
            "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
            "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
            "                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
            "    return len(records), 0\n",
            "           ^^^^^^^^^^^^\n",
            "TypeError: object of type 'NoneType' has no len()\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n",
            "    stb = value._render_traceback_()\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
            "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
            "    return f(*args, **kwargs)\n",
            "           ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
            "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
            "                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/inspect.py\", line 1739, in getinnerframes\n",
            "    traceback_info = getframeinfo(tb, context)\n",
            "                     ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/inspect.py\", line 1686, in getframeinfo\n",
            "    start = lineno - 1 - context//2\n",
            "            ~~~~~~~^~~\n",
            "TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'\n"
          ]
        }
      ],
      "source": [
        "#w0: initial vorticity\n",
        "#f: forcing term\n",
        "#visc: viscosity (1/Re)\n",
        "#T: final time\n",
        "#delta_t: internal time-step for solve (descrease if blow-up)\n",
        "#record_steps: number of in-time snapshots to record\n",
        "def navier_stokes_2d(w0, f, visc, T, delta_t=1e-4, record_steps=1):\n",
        "\n",
        "    #Grid size - must be power of 2\n",
        "    N = w0.size()[-1]\n",
        "\n",
        "    #Maximum frequency\n",
        "    k_max = math.floor(N/2.0)\n",
        "\n",
        "    #Number of steps to final time\n",
        "    steps = math.ceil(T/delta_t)\n",
        "\n",
        "    #Initial vorticity to Fourier space\n",
        "    w_h = torch.fft.fft2(w0)\n",
        "\n",
        "    #Forcing to Fourier space\n",
        "    f_h = torch.fft.fft2(f)\n",
        "\n",
        "    #If same forcing for the whole batch\n",
        "    if len(f_h.size()) < len(w_h.size()):\n",
        "        f_h = torch.unsqueeze(f_h, 0)\n",
        "\n",
        "    #Record solution every this number of steps\n",
        "    record_time = math.floor(steps/record_steps)\n",
        "\n",
        "    #Wavenumbers in y-direction\n",
        "    k_y = torch.cat((torch.arange(start=0, end=k_max, step=1, device=w0.device), torch.arange(start=-k_max, end=0, step=1, device=w0.device)), 0).repeat(N,1)\n",
        "    #Wavenumbers in x-direction\n",
        "    k_x = k_y.transpose(0,1)\n",
        "    #Negative Laplacian in Fourier space\n",
        "    lap = 4*(math.pi**2)*(k_x**2 + k_y**2)\n",
        "    lap[0,0] = 1.0\n",
        "    lap = lap.to(dtype=w_h.dtype, device=w_h.device)\n",
        "    lap = lap.unsqueeze(0)\n",
        "    #Dealiasing mask\n",
        "    dealias = torch.unsqueeze(torch.logical_and(torch.abs(k_y) <= (2.0/3.0)*k_max, torch.abs(k_x) <= (2.0/3.0)*k_max).float(), 0)\n",
        "\n",
        "\n",
        "    #Saving solution and time\n",
        "    sol = torch.zeros(*w0.size(), record_steps, device=w0.device)\n",
        "    sol_t = torch.zeros(record_steps, device=w0.device)\n",
        "\n",
        "    #Record counter\n",
        "    c = 0\n",
        "    #Physical time\n",
        "    t = 0.0\n",
        "    for j in range(steps):\n",
        "        #Stream function in Fourier space: solve Poisson equation\n",
        "        #psi_h = w_h.clone()\n",
        "        psi_h = w_h / lap\n",
        "        #psi_h[...,0] = psi_h[...,0]/lap\n",
        "        #psi_h[...,1] = psi_h[...,1]/lap\n",
        "\n",
        "        #Velocity field in x-direction = psi_y\n",
        "        #q = psi_h.clone()\n",
        "        #temp = q[...,0].clone()\n",
        "        #q[...,0] = -2*math.pi*k_y*q[...,1]\n",
        "        #q[...,1] = 2*math.pi*k_y*temp\n",
        "        q_h = 1j * 2 * math.pi * k_y * psi_h\n",
        "        q = torch.fft.ifft2(q_h).real\n",
        "\n",
        "        #Velocity field in y-direction = -psi_x\n",
        "        #v = psi_h.clone()\n",
        "        #temp = v[...,0].clone()\n",
        "        #v[...,0] = 2*math.pi*k_x*v[...,1]\n",
        "        #v[...,1] = -2*math.pi*k_x*temp\n",
        "        v_h = -1j * 2 * math.pi * k_x * psi_h\n",
        "        v = torch.fft.ifft2(v_h).real\n",
        "\n",
        "        #Partial x of vorticity\n",
        "        #w_x = w_h.clone()\n",
        "        #temp = w_x[...,0].clone()\n",
        "        #w_x[...,0] = -2*math.pi*k_x*w_x[...,1]\n",
        "        #w_x[...,1] = 2*math.pi*k_x*temp\n",
        "        w_x_h = 1j * 2 * math.pi * k_x * w_h\n",
        "        w_x = torch.fft.ifft2(w_x_h).real\n",
        "\n",
        "        #Partial y of vorticity\n",
        "        #w_y = w_h.clone()\n",
        "        #temp = w_y[...,0].clone()\n",
        "        #w_y[...,0] = -2*math.pi*k_y*w_y[...,1]\n",
        "        #w_y[...,1] = 2*math.pi*k_y*temp\n",
        "        w_y_h = 1j * 2 * math.pi * k_y * w_h\n",
        "        w_y = torch.fft.ifft2(w_y_h).real\n",
        "\n",
        "        #Non-linear term (u.grad(w)): compute in physical space then back to Fourier space\n",
        "        F_h = torch.fft.fft2(q*w_x + v*w_y)\n",
        "        dealias = dealias.to(dtype=F_h.dtype, device=F_h.device)\n",
        "\n",
        "        #Dealias\n",
        "        #F_h[...,0] = dealias* F_h[...,0]\n",
        "        #F_h[...,1] = dealias* F_h[...,1]\n",
        "        F_h = dealias * F_h\n",
        "\n",
        "        #Cranck-Nicholson update\n",
        "        #w_h[...,0] = (-delta_t*F_h[...,0] + delta_t*f_h[...,0] + (1.0 - 0.5*delta_t*visc*lap)*w_h[...,0])/(1.0 + 0.5*delta_t*visc*lap)\n",
        "        #w_h[...,1] = (-delta_t*F_h[...,1] + delta_t*f_h[...,1] + (1.0 - 0.5*delta_t*visc*lap)*w_h[...,1])/(1.0 + 0.5*delta_t*visc*lap)\n",
        "        numerator = -delta_t * F_h + delta_t * f_h + (1.0 - 0.5 * delta_t * visc * lap) * w_h\n",
        "        denominator = 1.0 + 0.5 * delta_t * visc * lap\n",
        "        w_h = numerator / denominator\n",
        "\n",
        "\n",
        "        #Update real time (used only for recording)\n",
        "        t += delta_t\n",
        "\n",
        "        if (j+1) % record_time == 0:\n",
        "            #Solution in physical space\n",
        "            w = torch.fft.ifft2(w_h).real\n",
        "\n",
        "            #Record solution and time\n",
        "            sol[...,c] = w\n",
        "            sol_t[c] = t\n",
        "\n",
        "            c += 1\n",
        "\n",
        "\n",
        "    return sol, sol_t\n",
        "\n",
        "\n",
        "device = torch.device('cuda')\n",
        "\n",
        "#Resolution\n",
        "s = 256\n",
        "sub = 1\n",
        "\n",
        "#Number of solutions to generate\n",
        "N = 100\n",
        "\n",
        "#Set up 2d GRF with covariance parameters\n",
        "GRF = GaussianRF(2, s, alpha=2.5, tau=7, device=device)\n",
        "\n",
        "#Forcing function: 0.1*(sin(2pi(x+y)) + cos(2pi(x+y)))\n",
        "t = torch.linspace(0, 1, s+1, device=device)\n",
        "t = t[0:-1]\n",
        "\n",
        "X, Y = torch.meshgrid(t, t, indexing='ij')\n",
        "f = 0.1*(torch.sin(2*math.pi*(X + Y)) + torch.cos(2*math.pi*(X + Y)))\n",
        "\n",
        "#Number of snapshots from solution\n",
        "record_steps = 100\n",
        "\n",
        "#Inputs\n",
        "a = torch.zeros(N, s, s)\n",
        "#Solutions\n",
        "u = torch.zeros(N, s, s, record_steps)\n",
        "\n",
        "#Solve equations in batches (order of magnitude speed-up)\n",
        "\n",
        "#Batch size\n",
        "bsize = 20\n",
        "\n",
        "c = 0\n",
        "t0 =default_timer()\n",
        "for j in range(N//bsize):\n",
        "\n",
        "    #Sample random feilds\n",
        "    w0 = GRF.sample(bsize)\n",
        "\n",
        "    #Solve NS\n",
        "    sol, sol_t = navier_stokes_2d(w0, f, 1e-3, 50.0, 1e-4, record_steps)\n",
        "\n",
        "    a[c:(c+bsize),...] = w0\n",
        "    u[c:(c+bsize),...] = sol\n",
        "\n",
        "    c += bsize\n",
        "    t1 = default_timer()\n",
        "    print(j, c, t1-t0)\n",
        "\n",
        "scipy.io.savemat('ns_data.mat', mdict={'a': a.cpu().numpy(), 'u': u.cpu().numpy(), 't': sol_t.cpu().numpy()})"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "fWn9Dc31DAGP"
      },
      "outputs": [],
      "source": []
    }
  ],
  "metadata": {
    "accelerator": "GPU",
    "colab": {
      "gpuType": "T4",
      "machine_shape": "hm",
      "provenance": [],
      "authorship_tag": "ABX9TyPjMuUpda4t3tWwMmvkT8+H",
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}